"""Generate synthetic Grid Operations (electric utility) data for Text2SQL demos.

Generates the grid-ops operational schema and synthetic data:
substations -> feeders -> transformers -> meters, plus
outages / scada_alarms / crew_dispatch_logs.

Usage:
    uv run python scripts/data_pipeline/generate_grid_ops_db.py

Writes: seed/migrations/003_seed_grid_ops.sql
"""

from __future__ import annotations

import random
from datetime import UTC, datetime, timedelta
from pathlib import Path

from faker import Faker

SEED = 42
OUT_PATH = Path(__file__).parent.parent.parent / "seed" / "migrations" / "003_seed_grid_ops.sql"

N_SUBSTATIONS = 50
N_FEEDERS = 500
N_TRANSFORMERS = 500
N_METERS = 500
N_OUTAGES = 500
N_ALARMS = 500
N_DISPATCH_LOGS = 500

REGIONS = ["Northeast", "Southeast", "Midwest", "Southwest", "Pacific", "Mountain West"]
SUBSTATION_TYPES = ["transmission", "distribution", "switching"]
# Voltage class is correlated with substation type — a distribution substation
# does not operate at a 345 kV class, and a transmission substation does not sit
# at 69 kV. Keeping these consistent matters because the generated documents
# state both facts in the same sentence.
VOLTAGE_BY_TYPE = {
    "transmission": [230, 345, 500],
    "distribution": [69, 115, 138],
    "switching": [115, 138, 230],
}
STATUSES_INFRA = ["in_service", "de-energized", "maintenance"]
# Feeders use their own status vocabulary (matching the column default).
STATUSES_FEEDER = ["energized", "de-energized", "maintenance"]
FEEDER_VOLTAGES_KV = [4, 12, 13.2, 25, 34.5]
MANUFACTURERS = ["Siemens", "ABB", "GE Vernova", "Eaton", "Schneider Electric", "Hitachi Energy"]
CUSTOMER_TYPES = ["residential", "commercial", "industrial"]
OUTAGE_CAUSES = [
    "vegetation contact",
    "equipment failure",
    "storm damage",
    "animal contact",
    "vehicle accident",
    "overload",
    "planned maintenance",
    "unknown",
]
ALARM_TYPES = [
    "overcurrent",
    "transformer overtemperature",
    "low oil level",
    "breaker trip",
    "voltage sag",
    "ground fault",
    "communication loss",
    "differential protection trip",
]
SEVERITIES = ["P1", "P2", "P3", "P4"]
CREW_NAMES = [
    "Crew Alpha", "Crew Bravo", "Crew Charlie", "Crew Delta", "Crew Echo",
    "Crew Foxtrot", "Crew Golf", "Crew Hotel", "Crew India", "Crew Juliet",
]


def esc(s: str) -> str:
    return s.replace("'", "''")


def rand_dt(start_days_ago: int, end_days_ago: int = 0) -> datetime:
    days = random.uniform(end_days_ago, start_days_ago)
    return datetime.now(UTC) - timedelta(days=days)


def sql_ts(dt: datetime | None) -> str:
    return "NULL" if dt is None else f"'{dt.strftime('%Y-%m-%d %H:%M:%S%z')}'"


def main() -> None:
    random.seed(SEED)
    fake = Faker()
    Faker.seed(SEED)

    lines: list[str] = []
    lines.append("-- =============================================================================")
    lines.append("-- 003_seed_grid_ops.sql")
    lines.append("-- Synthetic Grid Operations (electric utility) data for Text2SQL demos and")
    lines.append("-- advanced RAG eval.")
    lines.append("--")
    lines.append("-- Generated by scripts/data_pipeline/generate_grid_ops_db.py")
    lines.append("-- DO NOT EDIT BY HAND — regenerate with:")
    lines.append("--   uv run python scripts/data_pipeline/generate_grid_ops_db.py")
    lines.append("--")
    lines.append(
        "-- Tables: substations, feeders, transformers, meters, outages, "
        "scada_alarms, crew_dispatch_logs"
    )
    lines.append("-- =============================================================================")
    lines.append("")
    lines.append("-- Run after 001_create_users.sql")
    lines.append("")
    lines.append("-- ---------------------------------------------------------------------------")
    lines.append("-- DROP (idempotent re-run) - cascade handles FK deps")
    lines.append("-- ---------------------------------------------------------------------------")
    for tbl in [
        "crew_dispatch_logs", "scada_alarms", "outages", "meters",
        "transformers", "feeders", "substations",
    ]:
        lines.append(f"DROP TABLE IF EXISTS {tbl} CASCADE;")
    lines.append("")
    lines.append("-- ---------------------------------------------------------------------------")
    lines.append("-- CREATE")
    lines.append("-- ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("""CREATE TABLE substations (
    substation_id     SERIAL PRIMARY KEY,
    name              VARCHAR(128) UNIQUE NOT NULL,
    region            VARCHAR(64)  NOT NULL,
    voltage_class_kv  SMALLINT     NOT NULL,
    substation_type   VARCHAR(32)  NOT NULL,
    status            VARCHAR(32)  NOT NULL DEFAULT 'in_service',
    commissioned_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);""")
    lines.append("""
CREATE TABLE feeders (
    feeder_id      SERIAL PRIMARY KEY,
    substation_id  INTEGER REFERENCES substations(substation_id),
    name           VARCHAR(128) NOT NULL,
    voltage_kv     NUMERIC(5,1) NOT NULL,
    capacity_amps  SMALLINT     NOT NULL,
    status         VARCHAR(32)  NOT NULL DEFAULT 'energized',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);""")
    lines.append("""
CREATE TABLE transformers (
    transformer_id  SERIAL PRIMARY KEY,
    feeder_id       INTEGER REFERENCES feeders(feeder_id),
    asset_tag       VARCHAR(64)  NOT NULL,
    capacity_mva    NUMERIC(6,2) NOT NULL,
    manufacturer    VARCHAR(64)  NOT NULL,
    install_year    SMALLINT     NOT NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'in_service',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);""")
    lines.append("""
CREATE TABLE meters (
    meter_id       SERIAL PRIMARY KEY,
    feeder_id      INTEGER REFERENCES feeders(feeder_id),
    customer_type  VARCHAR(32)  NOT NULL,
    status         VARCHAR(32)  NOT NULL DEFAULT 'active',
    install_date   DATE         NOT NULL
);""")
    lines.append("""
CREATE TABLE outages (
    outage_id           SERIAL PRIMARY KEY,
    severity             VARCHAR(4)   NOT NULL,
    feeder_id            INTEGER REFERENCES feeders(feeder_id),
    cause                VARCHAR(64)  NOT NULL,
    started_at           TIMESTAMPTZ  NOT NULL,
    restored_at          TIMESTAMPTZ,
    mttr_minutes         INTEGER,
    customers_affected   INTEGER,
    rca_summary          TEXT
);""")
    lines.append("""
CREATE TABLE scada_alarms (
    alarm_id                SERIAL PRIMARY KEY,
    fired_at                TIMESTAMPTZ  NOT NULL,
    severity                VARCHAR(4)   NOT NULL,
    source_transformer_id   INTEGER REFERENCES transformers(transformer_id),
    alarm_type               VARCHAR(128) NOT NULL,
    resolved                BOOLEAN      NOT NULL DEFAULT FALSE
);""")
    lines.append("""
CREATE TABLE crew_dispatch_logs (
    log_id              SERIAL PRIMARY KEY,
    crew_name           VARCHAR(64)  NOT NULL,
    dispatched_at       TIMESTAMPTZ  NOT NULL,
    outage_id           INTEGER REFERENCES outages(outage_id),
    response_time_mins  INTEGER      NOT NULL
);""")
    lines.append("")
    lines.append("-- Useful indexes for Text2SQL query performance")
    lines.append("CREATE INDEX idx_feeders_substation        ON feeders(substation_id);")
    lines.append("CREATE INDEX idx_transformers_feeder        ON transformers(feeder_id);")
    lines.append("CREATE INDEX idx_meters_feeder               ON meters(feeder_id);")
    lines.append("CREATE INDEX idx_meters_status                ON meters(status);")
    lines.append("CREATE INDEX idx_outages_feeder               ON outages(feeder_id);")
    lines.append("CREATE INDEX idx_outages_severity             ON outages(severity);")
    lines.append("CREATE INDEX idx_alarms_fired_at              ON scada_alarms(fired_at);")
    lines.append("CREATE INDEX idx_alarms_severity              ON scada_alarms(severity);")
    lines.append("CREATE INDEX idx_dispatch_outage              ON crew_dispatch_logs(outage_id);")
    lines.append("")

    # ---- substations ----
    substation_ids = list(range(1, N_SUBSTATIONS + 1))
    used_names: set[str] = set()
    sub_rows = []
    for sid in substation_ids:
        while True:
            name = f"sub-{fake.city().lower().replace(' ', '')}-{sid:03d}"
            if name not in used_names:
                used_names.add(name)
                break
        region = random.choice(REGIONS)
        stype = random.choice(SUBSTATION_TYPES)
        voltage = random.choice(VOLTAGE_BY_TYPE[stype])
        status = random.choices(STATUSES_INFRA, weights=[85, 5, 10])[0]
        commissioned = rand_dt(3650, 30)
        sub_rows.append(
            f"  ({sid}, '{esc(name)}', '{region}', {voltage}, '{stype}', "
            f"'{status}', {sql_ts(commissioned)})"
        )
    lines.append(f"-- substations: {N_SUBSTATIONS} rows")
    lines.append(
        "INSERT INTO substations (substation_id, name, region, voltage_class_kv, "
        "substation_type, status, commissioned_at) VALUES"
    )
    lines.append(",\n".join(sub_rows) + ";")
    lines.append("")

    # ---- feeders ----
    feeder_ids = list(range(1, N_FEEDERS + 1))
    feeder_rows = []
    feeder_substation = {}
    for fid in feeder_ids:
        sub_id = random.choice(substation_ids)
        feeder_substation[fid] = sub_id
        name = f"feeder-{sub_id:03d}-{fid:04d}"
        voltage = random.choice(FEEDER_VOLTAGES_KV)
        capacity = random.randint(200, 1200)
        status = random.choices(STATUSES_FEEDER, weights=[88, 4, 8])[0]
        created = rand_dt(3000, 30)
        feeder_rows.append(
            f"  ({fid}, {sub_id}, '{esc(name)}', {voltage}, {capacity}, "
            f"'{status}', {sql_ts(created)})"
        )
    lines.append(f"-- feeders: {N_FEEDERS} rows")
    lines.append(
        "INSERT INTO feeders (feeder_id, substation_id, name, voltage_kv, "
        "capacity_amps, status, created_at) VALUES"
    )
    lines.append(",\n".join(feeder_rows) + ";")
    lines.append("")

    # ---- transformers ----
    transformer_ids = list(range(1, N_TRANSFORMERS + 1))
    transformer_rows = []
    for tid in transformer_ids:
        feeder_id = random.choice(feeder_ids)
        asset_tag = f"XFMR-{tid:05d}"
        capacity = round(random.uniform(2.5, 60.0), 2)
        manufacturer = random.choice(MANUFACTURERS)
        install_year = random.randint(1985, 2025)
        status = random.choices(STATUSES_INFRA, weights=[85, 6, 9])[0]
        created = rand_dt(3000, 30)
        transformer_rows.append(
            f"  ({tid}, {feeder_id}, '{asset_tag}', {capacity}, '{esc(manufacturer)}', "
            f"{install_year}, '{status}', {sql_ts(created)})"
        )
    lines.append(f"-- transformers: {N_TRANSFORMERS} rows")
    lines.append(
        "INSERT INTO transformers (transformer_id, feeder_id, asset_tag, capacity_mva, "
        "manufacturer, install_year, status, created_at) VALUES"
    )
    lines.append(",\n".join(transformer_rows) + ";")
    lines.append("")

    # ---- meters ----
    meter_ids = list(range(1, N_METERS + 1))
    meter_rows = []
    for mid in meter_ids:
        feeder_id = random.choice(feeder_ids)
        ctype = random.choices(CUSTOMER_TYPES, weights=[70, 22, 8])[0]
        status = random.choices(["active", "inactive", "disconnected"], weights=[90, 6, 4])[0]
        install_date = rand_dt(3650, 30).date()
        meter_rows.append(
            f"  ({mid}, {feeder_id}, '{ctype}', '{status}', '{install_date}')"
        )
    lines.append(f"-- meters: {N_METERS} rows")
    lines.append(
        "INSERT INTO meters (meter_id, feeder_id, customer_type, status, install_date) VALUES"
    )
    lines.append(",\n".join(meter_rows) + ";")
    lines.append("")

    # ---- outages ----
    outage_ids = list(range(1, N_OUTAGES + 1))
    outage_rows = []
    for oid in outage_ids:
        feeder_id = random.choice(feeder_ids)
        severity = random.choices(SEVERITIES, weights=[10, 25, 35, 30])[0]
        cause = random.choice(OUTAGE_CAUSES)
        started = rand_dt(365, 0)
        resolved_pct = random.random()
        if resolved_pct < 0.9:
            mttr = random.randint(8, 480)
            restored = started + timedelta(minutes=mttr)
        else:
            mttr = None
            restored = None
        customers_affected = random.randint(1, 4200)
        rca = f"{cause.capitalize()} on {fake.street_name()} feeder segment; restored via {'automatic reclose' if random.random() < 0.3 else 'manual crew switching'}."
        outage_rows.append(
            f"  ({oid}, '{severity}', {feeder_id}, '{esc(cause)}', {sql_ts(started)}, "
            f"{sql_ts(restored)}, {mttr if mttr is not None else 'NULL'}, "
            f"{customers_affected}, '{esc(rca)}')"
        )
    lines.append(f"-- outages: {N_OUTAGES} rows")
    lines.append(
        "INSERT INTO outages (outage_id, severity, feeder_id, cause, started_at, "
        "restored_at, mttr_minutes, customers_affected, rca_summary) VALUES"
    )
    lines.append(",\n".join(outage_rows) + ";")
    lines.append("")

    # ---- scada_alarms ----
    alarm_rows = []
    for aid in range(1, N_ALARMS + 1):
        transformer_id = random.choice(transformer_ids)
        severity = random.choices(SEVERITIES, weights=[8, 22, 40, 30])[0]
        alarm_type = random.choice(ALARM_TYPES)
        fired = rand_dt(365, 0)
        resolved = random.random() < 0.8
        alarm_rows.append(
            f"  ({aid}, {sql_ts(fired)}, '{severity}', {transformer_id}, "
            f"'{esc(alarm_type)}', {'TRUE' if resolved else 'FALSE'})"
        )
    lines.append(f"-- scada_alarms: {N_ALARMS} rows")
    lines.append(
        "INSERT INTO scada_alarms (alarm_id, fired_at, severity, source_transformer_id, "
        "alarm_type, resolved) VALUES"
    )
    lines.append(",\n".join(alarm_rows) + ";")
    lines.append("")

    # ---- crew_dispatch_logs ----
    dispatch_rows = []
    for lid in range(1, N_DISPATCH_LOGS + 1):
        outage_id = random.choice(outage_ids)
        crew = random.choice(CREW_NAMES)
        dispatched = rand_dt(365, 0)
        response_time = random.randint(5, 180)
        dispatch_rows.append(
            f"  ({lid}, '{esc(crew)}', {sql_ts(dispatched)}, {outage_id}, {response_time})"
        )
    lines.append(f"-- crew_dispatch_logs: {N_DISPATCH_LOGS} rows")
    lines.append(
        "INSERT INTO crew_dispatch_logs (log_id, crew_name, dispatched_at, outage_id, "
        "response_time_mins) VALUES"
    )
    lines.append(",\n".join(dispatch_rows) + ";")
    lines.append("")

    # fix sequences after explicit-id inserts
    lines.append("-- Reset sequences after explicit-id inserts")
    for tbl, id_col in [
        ("substations", "substation_id"),
        ("feeders", "feeder_id"),
        ("transformers", "transformer_id"),
        ("meters", "meter_id"),
        ("outages", "outage_id"),
        ("scada_alarms", "alarm_id"),
        ("crew_dispatch_logs", "log_id"),
    ]:
        lines.append(
            f"SELECT setval(pg_get_serial_sequence('{tbl}', '{id_col}'), "
            f"(SELECT MAX({id_col}) FROM {tbl}));"
        )
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
